Algoritmo "Tabuada-multiplicada-5"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/06/2023
Var
// Seção de Declarações das variáveis 
tabuada:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para tabuada de 1 ate 10 faca

  escreval(tabuada*5)
  
fimpara

Fimalgoritmo