Algoritmo "Tabuada-multiplicada-5"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/06/2023
Var
// Seção de Declarações das variáveis 
tabuada:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

tabuada <- 0

enquanto (tabuada < 51) faca

   escreval(tabuada)
   tabuada <- tabuada + 5

fimenquanto


Fimalgoritmo